from graphviz import Digraph

dot = Digraph(comment='Corrected Simulator Architecture', format='png')
dot.attr(rankdir='TB', splines='ortho')

# Nodes
dot.node('A', 'Host SSD\n(Cold Load)', shape='box', style='filled', fillcolor='#ff9', color='#333')
dot.node('B', 'Host DRAM\n(Hot Layers)', shape='box', style='filled', fillcolor='#ddf', color='#333')
dot.node('C', 'Main Compute Engine (CPU)', shape='box', style='filled', fillcolor='#bbf', color='#333')
dot.node('D', 'CXL Device DRAM\n(Cache Pool + LRU + Pinning)', shape='box', style='filled', fillcolor='#9f9', color='#333')
dot.node('E', 'CXL Device NAND\n(Spilled Layers)', shape='box', style='filled', fillcolor='#faa', color='#333')
dot.node('F', 'Layer Placement?', shape='diamond', style='filled', fillcolor='#fff', color='#333')
dot.node('G', 'Compute + Host DRAM Transfer', shape='box', style='filled', fillcolor='#ddf', color='#333')
dot.node('H', 'In Cache?', shape='diamond', style='filled', fillcolor='#fff', color='#333')
dot.node('I', 'Compute + CXL DRAM Transfer', shape='box', style='filled', fillcolor='#ddf', color='#333')
dot.node('J', 'Stall Until I/O Completes', shape='box', style='filled', fillcolor='#fff', color='#333')
dot.node('K', 'Trigger Immediate Fetch if Not Queued', shape='box', style='filled', fillcolor='#fff', color='#333')
dot.node('L', 'Look Ahead: Add Next 8 Layers\nto Fetch Queue if on NAND', shape='box', style='filled', fillcolor='#fff', color='#333')
dot.node('M', 'Fetch Request Queue', shape='box', style='filled', fillcolor='#fff', color='#333')
dot.node('N', 'Asynchronous I/O Thread Pool\n(4 Threads)', shape='box', style='filled', fillcolor='#f96', color='#333')
dot.node('O', 'Fetch Queue Empty?', shape='diamond', style='filled', fillcolor='#fff', color='#333')
dot.node('P', 'Pop Request → Fetch from NAND → Write to CXL DRAM', shape='box', style='filled', fillcolor='#faa', color='#333')
dot.node('Q', 'Update DeviceDRAMPool (LRU)', shape='box', style='filled', fillcolor='#9f9', color='#333')
dot.node('R', 'Notify CPU if Layer Ready', shape='box', style='filled', fillcolor='#fff', color='#333')
dot.node('S', 'Idle', shape='box', style='filled', fillcolor='#fff', color='#333')

# Edges
dot.edge('A', 'B', label='Initial Load')
dot.edge('B', 'C', label='Hot Layers')
dot.edge('C', 'F')
dot.edge('F', 'G', label='Host DRAM')
dot.edge('F', 'H', label='CXL DRAM')
dot.edge('H', 'I', label='Yes')
dot.edge('H', 'J', label='No')
dot.edge('F', 'J', label='CXL NAND')
dot.edge('J', 'K')
dot.edge('C', 'L')
dot.edge('L', 'M')
dot.edge('M', 'N')
dot.edge('N', 'O')
dot.edge('O', 'P', label='No')
dot.edge('O', 'S', label='Yes')
dot.edge('P', 'Q')
dot.edge('Q', 'R')
dot.edge('R', 'C')
dot.edge('E', 'P', label='Fetch From NAND')
dot.edge('P', 'D', label='Write to CXL DRAM')
dot.edge('D', 'C', label='Serve from Cache')

dot.render('corrected_simulator_architecture', cleanup=True)
print("✅ Image saved as 'corrected_simulator_architecture.png'")